"""API request and response schemas."""
from __future__ import annotations

from .requests import GenerateProjectRequest
from .responses import (
    AgentResultDetail,
    AllowedTransitionsResponse,
    ArtifactVersionItem,
    ArtifactVersionsResponse,
    CleanupResponse,
    ConsistencyIssueResponse,
    ConsistencyReportResponse,
    ErrorResponse,
    ExecutionCheckResult,
    ExecutionValidation,
    FeatureDetail,
    GenerateProjectResponse,
    HealthResponse,
    InfoResponse,
    PipelineDetails,
    ProjectDownloadInfo,
    ProjectListItem,
    ProjectListResponse,
    ProjectStatusResponse,
    RetentionResponse,
    ScaffoldValidation,
    TechStackDetail,
    TransitionResponse,
)

__all__ = [
    "AgentResultDetail",
    "AllowedTransitionsResponse",
    "ArtifactVersionItem",
    "ArtifactVersionsResponse",
    "CleanupResponse",
    "ConsistencyIssueResponse",
    "ConsistencyReportResponse",
    "ErrorResponse",
    "ExecutionCheckResult",
    "ExecutionValidation",
    "FeatureDetail",
    "GenerateProjectRequest",
    "GenerateProjectResponse",
    "HealthResponse",
    "InfoResponse",
    "PipelineDetails",
    "ProjectDownloadInfo",
    "ProjectListItem",
    "ProjectListResponse",
    "ProjectStatusResponse",
    "RetentionResponse",
    "ScaffoldValidation",
    "TechStackDetail",
    "TransitionResponse",
]
